# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUIs\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(391, 254)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/program_icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.currentRunnerGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.currentRunnerGroup.setGeometry(QtCore.QRect(10, 10, 141, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.currentRunnerGroup.setFont(font)
        self.currentRunnerGroup.setFlat(False)
        self.currentRunnerGroup.setCheckable(False)
        self.currentRunnerGroup.setObjectName("currentRunnerGroup")
        self.currentRunnerNr = QElidingLabel(self.currentRunnerGroup)
        self.currentRunnerNr.setGeometry(QtCore.QRect(20, 20, 111, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.currentRunnerNr.setFont(font)
        self.currentRunnerNr.setObjectName("currentRunnerNr")
        self.currentRunnerTime = QtWidgets.QLabel(self.currentRunnerGroup)
        self.currentRunnerTime.setGeometry(QtCore.QRect(20, 40, 111, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.currentRunnerTime.setFont(font)
        self.currentRunnerTime.setObjectName("currentRunnerTime")
        self.nextRunnerGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.nextRunnerGroup.setGeometry(QtCore.QRect(240, 10, 141, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.nextRunnerGroup.setFont(font)
        self.nextRunnerGroup.setObjectName("nextRunnerGroup")
        self.nextRunnerNr = QElidingLabel(self.nextRunnerGroup)
        self.nextRunnerNr.setGeometry(QtCore.QRect(20, 20, 111, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nextRunnerNr.setFont(font)
        self.nextRunnerNr.setObjectName("nextRunnerNr")
        self.nextRunnerTime = QtWidgets.QLabel(self.nextRunnerGroup)
        self.nextRunnerTime.setGeometry(QtCore.QRect(20, 40, 111, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nextRunnerTime.setFont(font)
        self.nextRunnerTime.setObjectName("nextRunnerTime")
        self.timerLabel = QtWidgets.QLabel(self.centralwidget)
        self.timerLabel.setGeometry(QtCore.QRect(120, 90, 151, 71))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.timerLabel.setFont(font)
        self.timerLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.timerLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.timerLabel.setLineWidth(1)
        self.timerLabel.setTextFormat(QtCore.Qt.PlainText)
        self.timerLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timerLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.timerLabel.setObjectName("timerLabel")
        self.startBtn = QtWidgets.QPushButton(self.centralwidget)
        self.startBtn.setEnabled(False)
        self.startBtn.setGeometry(QtCore.QRect(70, 190, 75, 23))
        self.startBtn.setObjectName("startBtn")
        self.stopBtn = QtWidgets.QPushButton(self.centralwidget)
        self.stopBtn.setEnabled(False)
        self.stopBtn.setGeometry(QtCore.QRect(160, 190, 75, 23))
        self.stopBtn.setFlat(False)
        self.stopBtn.setObjectName("stopBtn")
        self.resetBtn = QtWidgets.QPushButton(self.centralwidget)
        self.resetBtn.setEnabled(False)
        self.resetBtn.setGeometry(QtCore.QRect(250, 190, 75, 23))
        self.resetBtn.setObjectName("resetBtn")
        self.differenceGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.differenceGroup.setGeometry(QtCore.QRect(160, 20, 71, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.differenceGroup.setFont(font)
        self.differenceGroup.setAlignment(QtCore.Qt.AlignCenter)
        self.differenceGroup.setObjectName("differenceGroup")
        self.currentDifference = QtWidgets.QLabel(self.differenceGroup)
        self.currentDifference.setGeometry(QtCore.QRect(20, 20, 41, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.currentDifference.setFont(font)
        self.currentDifference.setObjectName("currentDifference")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 391, 21))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuData = QtWidgets.QMenu(self.menubar)
        self.menuData.setObjectName("menuData")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuDisplay = QtWidgets.QMenu(self.menubar)
        self.menuDisplay.setObjectName("menuDisplay")
        MainWindow.setMenuBar(self.menubar)
        self.action_fromFile = QtWidgets.QAction(MainWindow)
        self.action_fromFile.setObjectName("action_fromFile")
        self.action_fromMemory = QtWidgets.QAction(MainWindow)
        self.action_fromMemory.setObjectName("action_fromMemory")
        self.action_information = QtWidgets.QAction(MainWindow)
        self.action_information.setObjectName("action_information")
        self.action_settings = QtWidgets.QAction(MainWindow)
        self.action_settings.setObjectName("action_settings")
        self.action_runnerList = QtWidgets.QAction(MainWindow)
        self.action_runnerList.setObjectName("action_runnerList")
        self.action_bigTimer = QtWidgets.QAction(MainWindow)
        self.action_bigTimer.setObjectName("action_bigTimer")
        self.menuAbout.addAction(self.action_information)
        self.menuData.addAction(self.action_fromFile)
        self.menuData.addAction(self.action_fromMemory)
        self.menuSettings.addAction(self.action_settings)
        self.menuDisplay.addAction(self.action_runnerList)
        self.menuDisplay.addAction(self.action_bigTimer)
        self.menubar.addAction(self.menuData.menuAction())
        self.menubar.addAction(self.menuDisplay.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DuathlonStarter"))
        self.currentRunnerGroup.setTitle(_translate("MainWindow", "Bus paleistas"))
        self.currentRunnerNr.setText(_translate("MainWindow", "Dalyvis:"))
        self.currentRunnerTime.setText(_translate("MainWindow", "Laikas:"))
        self.nextRunnerGroup.setTitle(_translate("MainWindow", "Sekantis"))
        self.nextRunnerNr.setText(_translate("MainWindow", "Dalyvis:"))
        self.nextRunnerTime.setText(_translate("MainWindow", "Laikas:"))
        self.timerLabel.setText(_translate("MainWindow", "00:00,0"))
        self.startBtn.setText(_translate("MainWindow", "Pradėti"))
        self.stopBtn.setText(_translate("MainWindow", "Stabdyti"))
        self.resetBtn.setText(_translate("MainWindow", "Atstatyti"))
        self.differenceGroup.setTitle(_translate("MainWindow", "Skirtumas"))
        self.currentDifference.setText(_translate("MainWindow", "00:00,0"))
        self.menuAbout.setTitle(_translate("MainWindow", "Apie"))
        self.menuData.setTitle(_translate("MainWindow", "Duomenys"))
        self.menuSettings.setTitle(_translate("MainWindow", "Nustatymai"))
        self.menuDisplay.setTitle(_translate("MainWindow", "Vaizdas"))
        self.action_fromFile.setText(_translate("MainWindow", "Iš failo"))
        self.action_fromFile.setShortcut(_translate("MainWindow", "Ctrl+F"))
        self.action_fromMemory.setText(_translate("MainWindow", "Iš atminties"))
        self.action_fromMemory.setShortcut(_translate("MainWindow", "Ctrl+M"))
        self.action_information.setText(_translate("MainWindow", "Informacija"))
        self.action_settings.setText(_translate("MainWindow", "Nustatymai"))
        self.action_runnerList.setText(_translate("MainWindow", "Dalyvių sąrašas"))
        self.action_bigTimer.setText(_translate("MainWindow", "Didelis laikmatis"))

from QElidingLabel import QElidingLabel

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

